config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # user session has non-model backed routes
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/about', to: 'users#about', as: 'about'

  #get '/posts', to: 'posts#index'
  #get '/posts/:id', to: 'posts#show'
  #get '/posts/new', to: 'posts#new'
  #get '/posts', to: 'posts#create'
  #get '/posts/:id/edit', to: 'posts#edit'
  #patch '/posts/:id', to: 'posts#update'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
  	resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base
	include Sluggable
	has_many :posts
	has_many :comments
	has_many :votes

	has_secure_password validations: false

	validates :username, presence: true, uniqueness: true
	validates :password, presence: true, on: :create, length: {minimum: 5} # this validation only fires when you create a user (don't want to have to make a new password when updating)

	#before_save :generate_slug!

	# every time it will pull up the username in the URL
  
	sluggable_column :username


	def admin?
		self.role == 'admin'
	end

	def moderator?
		self.role == 'moderator?'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = 'You are registered for the site!'
			redirect_to root_path(@user)
		else
			render :new
		end
	end

	def edit
		@user = User.find_by slug: params[:id]
	end
	def update
		@user = User.find_by slug: params[:id]
		if @user.update(user_params)
      flash[:notice] = 'Update Successful!'
      redirect_to root_path(@user)
    else
      flash[:notice] = 'Failure to update, please enter correct paramaters'
      render :edit
    end
	end

	def show
		@user = User.find_by slug: params[:id]
	end

	def about
	end

	private
	def user_params
    params.require(:user).permit(:username, :password, :phone, :time_zone)
  end
end

app/views/users/_form.html.erb
<%= provide(:title, 'User') %>
<%= render 'shared/errors', obj: @user %>

<div class='well'>
</br>
<%= form_for @user do |f| %>
	<ul id='user_form'>
	<li><%= f.label :username %></li>
	<li><%= f.text_field :username %></li>
	<li><%= f.label :email %></li>
	<li><%= f.text_field :email %></li>
	<li><%= f.label :password %></li>
	<li><%= f.password_field :password %></li>
	<li>
		<li><%= f.label :time_zone %></li>
		<li><%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %></li>
	</li>
	<li><%= f.submit @user.new_record? ? 'Register' : 'update profile', class: 'btn btn-primary'%></li>
	</ul>
<% end %>
</div>

app/views/users/about.html.erb
<div style="text-align:center;">
	<%= render 'shared/content_title', title: 'About:' %>
</div>

<h4>A little bit about the Read-This-Board:</h4>
</br>

<div class="well">
</br>
	<p>This is a website where people can post a URL Link and a short description about their post. Users will need to register with the site in order to create posts and to comment on other people's posts.</p>
</div>

app/views/users/edit.html.erb
<%= provide(:title, 'Edit your profile') %>
<h4 style="text-align:center;">Edit Profile</h4>
<%= render 'form' %>

app/views/users/new.html.erb
<div style="text-align:center;">
	<%= render 'shared/content_title', title: 'Register:' %>
</div>

<h4>Please create an account:</h4>
</br>

<%= render 'form' %>

</br>
<h4>Already Have an Account?    <%= link_to 'Login Here', login_path %></h4>

app/views/users/show.html.erb
<div style="text-align:center;">
	<%= render 'shared/content_title', title: 'Profile:' %>
</div>

<%= provide(:title, "#{@user.username}") %>

</br>
<div id="profile-pic">
	<%= gravatar_image_tag(@user.email) %>
</div>
</br>
<div style="text-align:center;">
	<%= render 'shared/content_title', title: "#{@user.username}" %>
</div>

<div class='well'>
	<h4>Username: <%= @user.username %></h4>
	<h4>Time Zone: <%= @user.time_zone %></h4>
	<h4>Number of Posts: <%= @user.posts.count %></h4>
	<h4>Number of Comments: <%= @user.comments.count %></h4>

	<% if logged_in? == true && @user.id == current_user.id %>
		<h4><%= link_to 'Edit Profile', edit_user_path(current_user) %></h4>
	<% end %>
</div>

<h4><%= @user.username %>'s Website Posts: </h4>

<ul class='nav nav-tabs'>
	<li class='<%= 'active' if params[:tab].nil? %>' ></li>
	<li class='<%= 'active' if params[:tab]== 'comments' %>' ></li>
</ul>

<% if params[:tab].nil? ||  params[:tab] == 'posts'%>
	<% @user.posts.sort_by{|x| x.total_votes}.reverse.each do |post| %>
		<div class='span0 well text-center'> 
    <!--Makes the vote post path into a POST (there is a form built into the javascript) -->
    <%= link_to vote_post_path(post, vote: true), method: 'post' do %>
      <i class='icon-arrow-up'></i>
    <% end %>
    <br/>
    <span id='post_<%= post.id %>_votes'><%= post.total_votes %> votes</span>
    <br/>
    <%= link_to vote_post_path(post, vote: false), method: 'post' do %>
      <i class='icon-arrow-down'></i>
    <% end %>

		<% if logged_in? == true && @user.id == current_user.id %>
    	<br/>
    	<th><%= link_to 'Edit', edit_post_path(post) %> </th>
		<% end %>


  </div>
  <%= render 'posts/post', post: post %>
	<% end %>

<% elsif params[:tab] == 'comments' %>
	<% @user.comments.sort_by{|x| x.total_votes}.reverse.each do |comment| %>
		<%= render 'comments/comment', comment: comment, show_post: true %>
	<% end %>
<% end %>