config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # user session has non-model backed routes
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/about', to: 'users#about', as: 'about'

  #get '/posts', to: 'posts#index'
  #get '/posts/:id', to: 'posts#show'
  #get '/posts/new', to: 'posts#new'
  #get '/posts', to: 'posts#create'
  #get '/posts/:id/edit', to: 'posts#edit'
  #patch '/posts/:id', to: 'posts#update'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
  	resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update]

end

app/models/post.rb
class Post < ActiveRecord::Base

	include Voteable
	include Sluggable

	belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
	has_many :comments
	has_many :post_categories
	has_many :categories, through: :post_categories
	# polymorphic association:
	
	
	validates :title, presence: true, length: {minimum: 2}
	validates :description, presence: true
	validates :url, presence: true, uniqueness: true

	
	sluggable_column :title
	# after_validation :generate_slug
	#see activerecord callbacks for more info



	if Rails.env.development?
  	has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default_image1.jpg"
  else
	  has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default_image1.jpg",
									  	:storage => :dropbox,
									    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
									    :path => ":style/:id_:filename"
	end
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates_attachment_presence :image
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  # so people not logged in can't access and edit posts and comments
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  # retrieve in CRUD
  def index
  	# @post = Post.all.sort_by{|x| x.total_votes}.reverse
    # @post = Post.all
    @post = Post.order("id DESC").paginate(:page => params[:page], :per_page => 5)
    @users = User.all

  end
  def show
  	# @post = Post.find(params[:id])
  	render :show
  end

  # create in CRUD
  def new
  	@post = Post.new
  end
  def create
    # initialize the article with its respective attributes
    @post = Post.new(post_params)
    @post.creator = current_user #change once we have authentication

    if @post.save
      flash[:notice] = 'Your post was created'
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    #@post = Post.find(params[:id])
  end

  def update
    #@post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = 'Your post was updated successfully'
      redirect_to post_path(@post)
    else
      flash[:notice] = 'Failure to update your post'
      render :edit
    end
  end

  def destroy
  end

  def vote
    # a vote needs to get added to the votes db table
    # needs to specify vote(t or f) user_id, the voteable_type, the voteable_id
  
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
 
    # if the vote is valid, then the prompt will be HTML. If the vote is invalid, the prompt will be JS
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = 'Your vote was counted.'
        else
          flash[:error] = 'Your vote was not counted, you can only vote once on each post'
        end
        redirect_to :back
      end
      format.js
    end
  end

  private
  def post_params
    params.require(:post).permit(:image, :title, :url, :description, category_ids: [])
  end

  def set_post
    #@post = Post.find(params[:id])
    @post = Post.find_by slug: params[:id]
  end

  def require_creator
    if current_user != @post.creator
      access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
    end
  end 
end

app/views/posts/_form.html.erb
<%= provide(:title, 'post') %>
<%= render 'shared/errors', obj: @post %>

<div class="well">
</br>
	<%= form_for @post do |f| %>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<%= f.label :url %>
		<%= f.text_field :url %>
		<%= f.label :description %>
		<%= f.text_area :description, rows: 5 %>

  	<div class="form-group">
			<%= f.label :image %>
	    <%= f.file_field :image, class: "form-control" %>
  	</div>
  	</br>

		<div class='control-group'>
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
				<% cb.label(class: 'checkbox inline') {cb.check_box(class: 'checkbox') + cb.text} %>
			<% end %>
		</div>
		
		<%= f.submit(@post.new_record? ? 'Create post' : 'Update Post', class: 'btn btn-primary' )%>
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class='row'>
  <div class='span8 well'>
    <%= render post.categories %>
  
    </br>
    <%= image_tag post.image.url(:thumb), style: "float:left;padding-right:15px;padding-top:20px;padding-bottom:20px;padding-left:20px;" %>


    <h3><%= link_to post.url, fix_url(post.url) %></h3>
    <h4><%= link_to post.title, post_path(post) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small>at <%= display_datetime(post.created_at) %></small>
    </p>
    <small>
      <span>
     
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= provide(:title, 'edit ') %>
<%= render 'shared/content_title', title: 'Edit Post:' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= provide(:title, 'Welcome') %>

<% if logged_in? != true %>
  <h4>Welcome to the Read-This-Board! Please <%= link_to 'register', register_path %> or <%= link_to 'login', login_path %> to post and comment on the site!</h4>
  </br>
<% else %>
  <h4>The latest posts on the Read-This-Board:</h4>
  </br>
<% end %>

<div style="text-align:center;">
  <%= render 'shared/content_title', title: 'Post Feed:' %>
</div>

<% @post.each do |post| %>
  <% if logged_in? == true %>
    <div class='span0 well text-center'> 
      <!--Makes the vote post path into a POST (there is a form built into the javascript) -->
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <i class='icon-arrow-up'></i>
  <% end %>
    <br/>
    <span id='post_<%= post.slug %>_votes'><%= post.total_votes %> votes</span>
    <br/>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
      <i class='icon-arrow-down'></i>
<% end %>

<% if (logged_in? == true && post.creator == current_user) || current_user.admin? %>
    <br/>
    <th><%= link_to 'Edit', edit_post_path(post) %> </th>
<% end %>
    </div>
  <%= render "posts/post", post: post, show_post: true %>
 <% else %>
 <%= render "posts/post", post: post, show_post: true %>
 <% end %>
<% end %>

<div class="pagination">
  <%= will_paginate @post, renderer: BootstrapPagination::Rails %>
</div>

app/views/posts/new.html.erb
<%= provide(:title, 'new') %>

<div style="text-align:center;">
	<%= render 'shared/content_title', title: 'New Post:' %>
</div>

<h4>Fill in the following fields:</h4>
</br>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= provide(:title, "#{@post.title}") %>
<%= render 'shared/content_title', title: 'Selected post:' %>

<div class='well'>
	</br>
    <%= image_tag @post.image.url(:thumb), style: "float:left;padding-right:15px;padding-top:20px;padding-bottom:20px;padding-left:20px;" %>

	<h3><%= @post.title %></h3>
	<h5><%= @post.url %></h5>
	<p><%= @post.description %></p>
	<p>
    <span class='quiet'>posted by</span> <%= link_to @post.creator.username, user_path(@post.creator) %>
    <small>at <%= display_datetime(@post.created_at) %></small>
  </p>
	<% if (logged_in? == true && @post.creator == current_user) %>
		<table>
	  	<tr>
	    	<th><%= link_to 'Edit', edit_post_path %> </th>
	  	</tr>
		</table>
	<% end %>
</div>

<h5>Comments:</h5>
<!-- .reload for slug -->
<% @post.reload.comments.sort_by{|x| x.total_votes}.reverse.each do |comment| %>
	<%= render "comments/comment", comment: comment, show_post: false %>
<% end %>

<div class='well pull-left span5'>
	<%= render "comments/form" %>
</div>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
	$("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes %> votes")
<% else %>
	alert('You can only vote on a post once!');
<% end%>