config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # user session has non-model backed routes
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/about', to: 'users#about', as: 'about'

  #get '/posts', to: 'posts#index'
  #get '/posts/:id', to: 'posts#show'
  #get '/posts/new', to: 'posts#new'
  #get '/posts', to: 'posts#create'
  #get '/posts/:id/edit', to: 'posts#edit'
  #patch '/posts/:id', to: 'posts#update'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
  	resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update]

end

app/models/category.rb
class Category < ActiveRecord::Base
	include Sluggable
	has_many :post_categories
	has_many :posts, through: :post_categories

	validates :name, presence: true
  validates :name, uniqueness: true
 
 	sluggable_column :name

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :require_user, except: [:show]
	before_action :require_admin, only: [:new, :create]

	def new
		@category = Category.new
	end
	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = 'Category has been created'
			redirect_to root_path
		else
			render :new
		end
	end

	def show
		@category = Category.find_by slug: params[:id]
	end

	# the only thing we want people to create is the 'name' of the category
	private
	def category_params
		params.require(:category).permit(:name)
	end

end

app/views/categories/_category.html.erb
<span class='badge'><%= category.name %></span>

app/views/categories/new.html.erb
<%= provide(:title, 'new category') %>
<%= render 'shared/content_title', title: 'new category:' %>
<%= render 'shared/errors', obj: @category %>

<div class='well'>
  <%= form_for @category do |f| %>
    <div class='control-group'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit 'create category', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/categories/show.html.erb
<%= provide(:title, "#{@category.name}") %>
<%= render 'shared/content_title', title: "Showing category: #{@category.name}" %>

<% @category.posts.each do |post| %>
	<div class='row'>
    <div class='span8 well'>
    <%= render post.categories %>

    <h4><%= link_to post.url, fix_url(post.url) %></h4>
    <h4><%= post.title %></h4>
    <p><%= post.description %> </p>
    <p>
      <span class='quiet'>posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small>at <%= display_datetime(post.created_at) %></small>
    </p>
    <small>
    <span>
      <%= link_to("#{post.comments.size} comments", post_path(post)) %>
    </span>
  </small>
</div>
</div>
<% end %>