config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # user session has non-model backed routes
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/about', to: 'users#about', as: 'about'

  #get '/posts', to: 'posts#index'
  #get '/posts/:id', to: 'posts#show'
  #get '/posts/new', to: 'posts#new'
  #get '/posts', to: 'posts#create'
  #get '/posts/:id/edit', to: 'posts#edit'
  #patch '/posts/:id', to: 'posts#update'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
  	resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update]

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
  </br>
	</br>
    <div class="footer-block"><div style="text-align:right;">Copyright 2015 Read-This-Board | <%= link_to 'About us',about_path %> | <%= link_to 'Privacy Policy',about_path %> | <%= link_to 'Terms/Conditions',about_path %> | <%= link_to 'Community',about_path %></div></div>
  </br>
 	</div>
</div>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54696917-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Read-This-Board', root_path, class: 'brand' %>
    </div>
    <div>
      <ul class="nav navbar-nav pull-right">
        <% if logged_in? %>
          <li><%= link_to 'HOME', root_path %></li>
          <li><%= link_to 'ABOUT', about_path %></li>
          <li><%= link_to 'NEW POST', new_post_path %></li>
          <li><%= link_to 'PROFILE', user_path(current_user) %></li>
          <li><%= link_to 'LOGOUT', logout_path %></li>
        <% else %>
          <li><%= link_to 'HOME', root_path %></li>
          <li><%= link_to 'ABOUT', about_path %></li>
          <li><%= link_to 'REGISTER', register_path %></li> 
          <li><%= link_to 'LOGIN', login_path %></li> 
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->

    <% if Rails.env.production? %>
      <%= render :partial => 'layouts/ga' %>
    <%end%>
    <%= render 'layouts/footer' %>
  </body>
</html>